[package]
name = "kafka-web"
version = "0.1.0"
authors = ["Federico Giraud <giraud.federico@gmail.com>"]

[dependencies]
byteorder = "1"
chrono = { version = "^0.3.0", features = ["serde"] }
clap = "2.18.0"
curl = "^0.4.2"
env_logger = "^0.3.0"
error-chain = "^0.9.0"
futures = "0.1.7"
futures-cpupool = "0.1.2"
iron = "^0.5.0"
iron_compress = "^0.1.3"
itertools = "^0.5.9"
log = "^0.3.0"
maud = { version = "0.16.1", features = ["iron"] }
maud_macros = "0.16.1"
mount = "^0.3.0"
rand = "0.3"
rdkafka = { git = "https://github.com/fede1024/rust-rdkafka.git"}
# rdkafka = "0.7.0"
regex = "0.1.80"
router = "^0.5.1"
serde = "^0.9.8"
serde-transcode = "^0.2.1"
serde_cbor = "^0.5.2"
serde_derive = "^0.9.8"
serde_json = "^0.9.8"
serde_yaml = "^0.6.2"
staticfile = { version = "^0.4.0", features = ["cache"] }
typemap = "0.3.3"
urlencoded = "0.4.1"
