[package]
name = "kafka-web"
version = "0.1.0"
authors = ["Federico Giraud <giraud.federico@gmail.com>"]

[dependencies]
chrono = { version = "0.2", features = ["serde"] }
clap = "2.18.0"
env_logger = "0.3.0"
error-chain = "0.7.1"
futures = "0.1.7"
futures-cpupool = "0.1.2"
iron = "0.4.0"
log = "0.3.0"
maud = { version = "*", features = ["iron"] }
maud_macros = "*"
mount = "0.2.1"
# rdkafka = "0.6.0"
rdkafka = { path = "/home/fede/rust/rust-rdkafka", version = "0.6.0" }
regex = "0.1.80"
router = "0.4.0"
serde = "0.8.0"
serde-transcode = "0.1.1"
serde_cbor = "0.4.0"
serde_derive = "0.8.0"
serde_json = "0.8.0"
serde_yaml = "0.5.0"
staticfile = "0.3.0"
typemap = "0.3.3"
urlencoded = "0.4.1"
curl = "0.4.2"
