[package]
name = "kafka-view"
version = "0.1.0"
authors = ["Federico Giraud <giraud.federico@gmail.com>"]

[dependencies]
byteorder = "1"
chrono = { version = "^0.3.0", features = ["serde"] }
clap = "2.18.0"
curl = "^0.4.2"
env_logger = "^0.3.0"
error-chain = "^0.10.0"
futures = "^0.1.11"
futures-cpupool = "^0.1.5"
iron = "^0.5.0"
iron_compress = "^0.1.3"
itertools = "^0.5.9"
lazy_static = "0.2.4"
log = "^0.3.0"
maud = { version = "0.16.1", features = ["iron"] }
maud_macros = "0.16.1"
mount = "^0.3.0"
urlencoded = "0.5.0"
rand = "0.3"
rdkafka = { git = "https://github.com/fede1024/rust-rdkafka.git"}
# rdkafka = { path = "/home/fede/rust/rust-rdkafka"}
# scheduled-executor = { path = "/home/fede/rust/scheduled-executor"}
scheduled-executor = { git = "https://github.com/fede1024/rust_scheduled_executor.git"}
# rdkafka = "^0.8.0"
regex = "0.1.80"
router = "^0.5.1"
serde = "^0.9.8"
serde-transcode = "^0.2.1"
serde_cbor = "^0.5.2"
serde_derive = "^0.9.8"
serde_json = "^0.9.8"
serde_yaml = "^0.6.2"
staticfile = { version = "^0.4.0", features = ["cache"] }
typemap = "0.3.3"
