[package]
name = "kafka-web"
version = "0.1.0"
authors = ["Federico Giraud <giraud.federico@gmail.com>"]

[dependencies]
env_logger = "^0.3.0"
error-chain = "^0.7.1"
clap = "2.18.0"
log = "^0.3.0"
rdkafka = { path = "/home/fede/rust/rust-rdkafka", version = "^0.5.0" }
serde = "^0.8.0"
serde_derive = "^0.8.0"
serde_json = "^0.8.0"
serde_yaml = "^0.5.0"
futures = "*"
futures-cpupool = "*"
