[package]
name = "kafka-view"
version = "0.1.0"
authors = ["Federico Giraud <giraud.federico@gmail.com>"]

[dependencies]
byteorder = "1"
chrono = { version = "^0.3.0", features = ["serde"] }
clap = "2.18.0"
curl = "^0.4.2"
env_logger = "^0.3.0"
error-chain = "^0.10.0"
futures = "^0.1.14"
futures-cpupool = "^0.1.5"
lazy_static = "0.2.4"
log = "^0.3.0"
maud = { version = "0.16.2", features = ["rocket"] }
maud_macros = "0.16.3"
rand = "0.3"
rdkafka = "^0.12.0"
# rdkafka = { path = "/home/fede/rust/rust-rdkafka"}
# rdkafka = { git = "https://github.com/fede1024/rust-rdkafka.git"}
regex = "0.1.80"
rocket = "0.2.6"
rocket_codegen = "0.2.6"
scheduled-executor = "^0.3.0"
# scheduled-executor = { git = "https://github.com/fede1024/rust_scheduled_executor.git"}
# scheduled-executor = { path = "/home/fede/rust/scheduled-executor"}
serde = "^0.9.8"
serde-transcode = "^0.2.1"
serde_cbor = "^0.5.2"
serde_derive = "^0.9.8"
serde_json = "^0.9.8"
serde_yaml = "^0.6.2"
