---
  metadata_refresh: 60
  metrics_refresh: 600
  caching:
    cluster: local_cluster
    topic: replicator_topic

  clusters:
    local_cluster:
      broker_list:
        - localhost:9092
      zookeeper: localhost
